spring:
  datasource:
      url: jdbc:mysql:///sell?serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
      host: 129.28.33.228
  redis:
      host: 129.28.33.228
      port: 6379
value: ltl
